
OK = "OK"
INVALID_ARGS = "INVALID_ARGS"
INVALID_MOVE = "INVALID_MOVE"
NOT_SUPPORTED = "NOT_SUPPORTED"
UNKNOWN_COMMAND = "UNKNOWN_COMMAND"
NOT_REGISTERED = "NOT_REGISTERED"
GAME_OVER = "GAME_OVER"
INTERNAL_ERROR = "INTERNAL_ERROR"
